# Generated by Django 3.0.4 on 2020-03-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antcf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='grocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('medic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='info_naissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('pc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='malade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('csg', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.CharField(max_length=20)),
                ('taille', models.CharField(max_length=20)),
                ('pc', models.CharField(max_length=20)),
                ('examenclinique', models.TextField()),
                ('malade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nardjes1.malade')),
            ],
        ),
        migrations.CreateModel(
            name='antcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.TextField()),
                ('par', models.TextField()),
                ('vac', models.TextField()),
                ('lait', models.TextField()),
                ('dpm', models.TextField()),
                ('path', models.TextField()),
                ('thera', models.TextField()),
                ('grocess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nardjes1.grocess')),
                ('infos_naisssnace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nardjes1.info_naissance')),
            ],
        ),
    ]
